//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int ID_BINHLUAN { get; set; }
        public int ID_USER { get; set; }
        public int ID_SANPHAM { get; set; }
        public System.DateTime NGAY { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual USER USER { get; set; }
    }
}
