//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DATHANG
    {
        public int ID_CTDH { get; set; }
        public int ID_ODER { get; set; }
        public int ID_SANPHAM { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
