//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        public DATHANG()
        {
            this.CT_DATHANG = new HashSet<CT_DATHANG>();
        }
    
        public int ID_ODER { get; set; }
        public string USRERNAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    
        public virtual ICollection<CT_DATHANG> CT_DATHANG { get; set; }
    }
}
