//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIEN_HE
    {
        public int ID_LH { get; set; }
        public string INFO_1 { get; set; }
        public string INFO_2 { get; set; }
        public string INFO_3 { get; set; }
        public string OURADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
    }
}
