//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGER
    {
        public int ID_MANAGER { get; set; }
        public string LOGINNAME { get; set; }
        public string PASS { get; set; }
        public string USERNAME { get; set; }
        public string IMAGE1 { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
    }
}
