//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI_GOPY
    {
        public int ID_PH_GOPY { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string NOIDUNG { get; set; }
    }
}
