//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CT_DATHANG = new HashSet<CT_DATHANG>();
        }
    
        public int ID_SANPHAM { get; set; }
        public int ID_CATALOGY { get; set; }
        public int ID_NHASX { get; set; }
        public string TENSP { get; set; }
        public int ID_SIZE { get; set; }
        public decimal GIA { get; set; }
        public decimal SALE { get; set; }
        public string MAUSAC { get; set; }
        public string MOTA { get; set; }
        public string IMAGE1 { get; set; }
        public string IMAGE2 { get; set; }
        public string IMAGE3 { get; set; }
        public string IMAGE4 { get; set; }
        public int SOLUONG { get; set; }
        public System.DateTime NGAY { get; set; }
        public string TAGS { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual CATALOGY CATALOGY { get; set; }
        public virtual NHASX NHASX { get; set; }
        public virtual ICollection<CT_DATHANG> CT_DATHANG { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
