//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEO
    {
        public int ID_SEO { get; set; }
        public string TITLES { get; set; }
        public string DESCRIPTIONS { get; set; }
        public System.DateTime KEYWORDS { get; set; }
    }
}
