//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIZE
    {
        public SIZE()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int ID_SIZE { get; set; }
        public string SIZE1 { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
