//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
        }
    
        public int ID_USER { get; set; }
        public string LOGINNAME { get; set; }
        public string PASS { get; set; }
        public string USERNAME { get; set; }
        public string DT { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
    }
}
